### ISSUE TITLE
docker-compose error on stable

### ISSUE THREAD

**Issue by sergey27564** [unpoller/unpoller#376]
Error appears on versions latest, stable, 2, 2.0.1, some others, using prometheus not helps, returns similar error

```
up-poller    | panic: runtime error: invalid memory address or nil pointer dereference
up-poller    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x3fae90]
up-poller    | 
up-poller    | goroutine 6 [running]:
up-poller    | github.com/unifi-poller/influxunifi.(*InfluxUnifi).batchUXG(0x1100240, 0x6b404c, 0x10662d0, 0x18c0000)
up-poller    | 	/go/pkg/mod/github.com/unifi-poller/influxunifi@v0.0.0-20210418074400-d2de22bd896d/uxg.go:30 +0x3a4
up-poller    | github.com/unifi-poller/influxunifi.(*InfluxUnifi).switchExport(0x1100240, 0x6b404c, 0x10662d0, 0x5b6eb8, 0x18c0000)
up-poller    | 	/go/pkg/mod/github.com/unifi-poller/influxunifi@v0.0.0-20210418074400-d2de22bd896d/influxdb.go:280 +0x244
up-poller    | github.com/unifi-poller/influxunifi.(*InfluxUnifi).loopPoints(0x1100240, 0x6b404c, 0x10662d0)
up-poller    | 	/go/pkg/mod/github.com/unifi-poller/influxunifi@v0.0.0-20210418074400-d2de22bd896d/influxdb.go:252 +0x218
up-poller    | github.com/unifi-poller/influxunifi.(*InfluxUnifi).ReportMetrics(0x1100240, 0x106d2c0, 0x16822d0, 0x0, 0x0, 0x0)
up-poller    | 	/go/pkg/mod/github.com/unifi-poller/influxunifi@v0.0.0-20210418074400-d2de22bd896d/influxdb.go:200 +0x248
up-poller    | github.com/unifi-poller/influxunifi.(*InfluxUnifi).PollController(0x1100240)
up-poller    | 	/go/pkg/mod/github.com/unifi-poller/influxunifi@v0.0.0-20210418074400-d2de22bd896d/influxdb.go:96 +0x388
up-poller    | github.com/unifi-poller/influxunifi.(*InfluxUnifi).Run(0x1100240, 0x6b407c, 0x1208120, 0x0, 0x0)
up-poller    | 	/go/pkg/mod/github.com/unifi-poller/influxunifi@v0.0.0-20210418074400-d2de22bd896d/influxdb.go:132 +0x288
up-poller    | github.com/unifi-poller/poller.(*UnifiPoller).runOutputMethods.func1(0x104c640, 0x1208120, 0x11362d0)
up-poller    | 	/go/pkg/mod/github.com/unifi-poller/poller@v0.0.0-20210418074507-efda34dd8222/outputs.go:85 +0x30
up-poller    | created by github.com/unifi-poller/poller.(*UnifiPoller).runOutputMethods
up-poller    | 	/go/pkg/mod/github.com/unifi-poller/poller@v0.0.0-20210418074507-efda34dd8222/outputs.go:84 +0xc0
up-poller exited with code 2
```

**Comment by sergey27564** [comment]
Problem while processing uxg, it's not appears in 2.0.0, just skips it.

**Comment by davidnewhall** [comment]
When did this start? Did your controller upgrade?

**Comment by platinummonkey** [comment]
this was fixed
