### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by neilmunday** [unpoller/unpoller#545]
unpoller version: 2.7.12
Unifi device: Unifi Dream Machine, OS: 2.5.17

```
Apr 15 20:40:54 bob unpoller[286126]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 15 20:40:54 bob unpoller[286126]: #011panic: runtime error: invalid memory address or nil pointer dereference
Apr 15 20:40:54 bob unpoller[286126]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x837bda]
Apr 15 20:40:54 bob unpoller[286126]: goroutine 988 [running]:
Apr 15 20:40:54 bob unpoller[286126]: github.com/unpoller/unpoller/pkg/inputunifi.formatSites(...)
Apr 15 20:40:54 bob unpoller[286126]: #011/home/runner/work/unpoller/unpoller/pkg/inputunifi/updateweb.go:70
Apr 15 20:40:54 bob unpoller[286126]: github.com/unpoller/unpoller/pkg/inputunifi.updateWeb(0xc0000aec18, 0xc000407c68)
Apr 15 20:40:54 bob unpoller[286126]: #011/home/runner/work/unpoller/unpoller/pkg/inputunifi/updateweb.go:17 +0x15a
Apr 15 20:40:54 bob unpoller[286126]: panic({0xaf90e0, 0x10d5700})
Apr 15 20:40:54 bob unpoller[286126]: #011/opt/hostedtoolcache/go/1.20.2/x64/src/runtime/panic.go:884 +0x213
Apr 15 20:40:54 bob unpoller[286126]: github.com/unpoller/unifi.(*Unifi).GetClients(0x0, {0xc0000230c0, 0x1, 0x0?})
Apr 15 20:40:54 bob unpoller[286126]: #011/home/runner/go/pkg/mod/github.com/unpoller/unifi@v0.3.2/clients.go:17 +0x170
Apr 15 20:40:54 bob unpoller[286126]: github.com/unpoller/unpoller/pkg/inputunifi.(*InputUnifi).pollController(0xc00008f0e0, 0xc0000aec18)
Apr 15 20:40:54 bob unpoller[286126]: #011/home/runner/work/unpoller/unpoller/pkg/inputunifi/collector.go:114 +0x625
Apr 15 20:40:54 bob unpoller[286126]: github.com/unpoller/unpoller/pkg/inputunifi.(*InputUnifi).collectController(0x465069?, 0xc0000aec18)
Apr 15 20:40:54 bob unpoller[286126]: #011/home/runner/work/unpoller/unpoller/pkg/inputunifi/collector.go:71 +0xfb
Apr 15 20:40:54 bob unpoller[286126]: github.com/unpoller/unpoller/pkg/inputunifi.(*InputUnifi).Metrics(0xc00008f0e0, 0x0)
Apr 15 20:40:54 bob unpoller[286126]: #011/home/runner/work/unpoller/unpoller/pkg/inputunifi/interface.go:174 +0x16a
Apr 15 20:40:54 bob unpoller[286126]: github.com/unpoller/unpoller/pkg/poller.(*unpoller).Metrics.func1(0xc0005717a0?)
Apr 15 20:40:54 bob unpoller[286126]: #011/home/runner/work/unpoller/unpoller/pkg/poller/inputs.go:194 +0xef
Apr 15 20:40:54 bob unpoller[286126]: created by github.com/unpoller/unpoller/pkg/poller.(*unpoller).Metrics
Apr 15 20:40:54 bob unpoller[286126]: #011/home/runner/work/unpoller/unpoller/pkg/poller/inputs.go:185 +0x111
Apr 15 20:40:54 bob systemd[1]: unpoller.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 15 20:40:54 bob systemd[1]: unpoller.service: Failed with result 'exit-code'.
```

**Comment by platinummonkey** [comment]
Can you share your config?

**Comment by neilmunday** [comment]
Here's my config (password changed to *unifipoller*, url changed, comments removed):

```
[poller]
  debug = false
  quiet = false
  plugins = []

[prometheus]
  disable = false
  http_listen = "0.0.0.0:9130"
  ssl_cert_path = ""
  ssl_key_path  = ""
  report_errors = true
  dead_ports = false

[influxdb]
  disable = true
  url  = "http://127.0.0.1:8086"
  user = "unifipoller"
  pass = "unifipoller"
  db = "unifi"
  verify_ssl = false
  interval = "30s"
  dead_ports = false

[loki]
  url = ""
  user       = ""
  pass       = ""
  verify_ssl = false
  tenant_id  = ""
  interval   = "2m"
  timeout    = "10s"

[webserver]
  enable = false
  port   = 37288
  html_path     = "/usr/lib/unifi-poller/web"
  ssl_cert_path = ""
  ssl_key_path  = ""
  max_events = 200

[webserver.accounts]

[unifi]
  dynamic = false

[unifi.defaults]
  url = "https://router.example.com"
  user = "unifipoller"
  pass = "unifipoller"
  sites = ["all"]
  save_sites = true
  hash_pii = false
  save_ids = false
  save_events = false
  save_alarms = false
  save_anomalies = false
  save_dpi = false
  save_rogue = false
  verify_ssl = false
  ssl_cert_paths = []
```

**Comment by neilmunday** [comment]
Just to add, `unpoller` does run but it can crash from time to time.

**Comment by platinummonkey** [comment]
I believe I've fixed this in later releases, is this still happening in v2.8.1?

**Comment by neilmunday** [comment]
Apologies for the delay in replying. I've just updated to version 2.10.0 and will keep any eye on the logs.
